// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsR5f6TnqyNE6Jzzn02x_tsJQZWYUQ3sQ',
    appId: '1:762949259477:web:e150bd4faae7e10a0b525c',
    messagingSenderId: '762949259477',
    projectId: 'recipe-recommendation-ap-a03df',
    authDomain: 'recipe-recommendation-ap-a03df.firebaseapp.com',
    storageBucket: 'recipe-recommendation-ap-a03df.firebasestorage.app',
    measurementId: 'G-MLMMNFZEGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKbHRnBpXn37OrMhKFz_rtLML_1UHWxB0',
    appId: '1:762949259477:android:414fdfd5264bbe450b525c',
    messagingSenderId: '762949259477',
    projectId: 'recipe-recommendation-ap-a03df',
    storageBucket: 'recipe-recommendation-ap-a03df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCrZh1-jf0FyG40ST-SOu3n0hsUq9BBYs',
    appId: '1:762949259477:ios:2b62ccaeb97a0ae90b525c',
    messagingSenderId: '762949259477',
    projectId: 'recipe-recommendation-ap-a03df',
    storageBucket: 'recipe-recommendation-ap-a03df.firebasestorage.app',
    iosBundleId: 'com.example.recipeRecommendation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCrZh1-jf0FyG40ST-SOu3n0hsUq9BBYs',
    appId: '1:762949259477:ios:2b62ccaeb97a0ae90b525c',
    messagingSenderId: '762949259477',
    projectId: 'recipe-recommendation-ap-a03df',
    storageBucket: 'recipe-recommendation-ap-a03df.firebasestorage.app',
    iosBundleId: 'com.example.recipeRecommendation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsR5f6TnqyNE6Jzzn02x_tsJQZWYUQ3sQ',
    appId: '1:762949259477:web:64def4a8fbe7e2f80b525c',
    messagingSenderId: '762949259477',
    projectId: 'recipe-recommendation-ap-a03df',
    authDomain: 'recipe-recommendation-ap-a03df.firebaseapp.com',
    storageBucket: 'recipe-recommendation-ap-a03df.firebasestorage.app',
    measurementId: 'G-EGWBH9FFV1',
  );
}
